DELETE FROM USUARIOS WHERE USER_ID = 1;
INSERT INTO USUARIOS (APELLIDO,NOMBRE,MAIL,CELULAR,LOGIN,PASSWORD,LEGAJO,ID_CARGO,TIPO_USUARIO,user_alta)
VALUES ('Schwarz','sDavid','davidschwarz@gmail.com',11111111,'sDavid','$2y$10$FjoDm3ua0BXdj4sBRCYf4O6OWwaciDv07/8AAcCFBdKr8dC/StWaO',1,10,1,1);
